### ISSUE TITLE
Installation with conda

### ISSUE THREAD

**Issue by awvwgk** [dftbplus/skprogs#1]
Just a few notes on what I found out while working with `conda` on this, installing dependencies and building is quite straight-forward with the currently available `libxc` package on conda-forge (if the version is selected correctly):

```
mamba create -n libxc-4 'libxc=4.*' -c conda-forge
mamba activate libxc-4
export PKG_CONFIG_PATH=$CONDA_PREFIX/lib/pkgconfig/:$PKG_CONFIG_PATH
cmake -B _build -G Ninja
ninja -C _build
```

There is another potentially compatible version of libxc in the psi4 channel, which provides the CMake module files, but no Fortran interface.

**Comment by hsulab** [comment]
The conda libxc seems to be built on `gcc-9.3.0`. Therefore, `skprogs` must be compiled with the gcc compiler while yielding few warnings like `Warning: Fortran 2018 deleted feature: DO termination statement which is not END DO or CONTINUE with label 38 at (1)` and `Warning: Extension: Unary operator following arithmetic operator (use parentheses) at (1)`.
