### ISSUE TITLE
The effects and function of CustomizedHubbards / skf structure

### ISSUE THREAD

**Issue by andrewshyichuk** [dftbplus/skprogs#102]
Are CustomizedHubbards the initial values, or the fixed values?

As I understand, the code calculates Hubbard values at skgen.atom. 

On the other end, I get this error in DFTB+ (not googleable):
-> Failure in short-range gamma, U too small :    0.187299    0.000000
[skdef.hsd.txt](https://github.com/user-attachments/files/17489645/skdef.hsd.txt)

Apparently, the problem is in the Hubbard U value being zero. And my idea is: provide some small initial value to remove the said zero - which would only work if CustomizedHubbards are the initial values. 

Alternatively, where do I modify the Hubbard U values in the skf file?

**Comment by aradi** [comment]
You are likely setting the wrong `MaxAngularMomentum` in the code. If your setting is higher as the one used when generating the SK-file, DFTB+ will read a placeholder entry with 0, which is an invalid value. The skprogs tool calculates the Hubbard U values for all relevant shells, and none of those values should be 0.

The Hubbard U values are not "initial values", they keep their value during the entire run.

**Comment by andrewshyichuk** [comment]
Dear aradi, 
Thank you, that indeed was the case. I had Lu valence shells "6s 6p 5d" in the skdef.hsd file, and then used max angular momentum f in DFTB+. Fixed, works!
