### ISSUE TITLE
sktools calling issue in skprogs

### ISSUE THREAD

**Issue by RameshwarKumawat** [dftbplus/skprogs#63]
Hello,

I did the installation of skprogs to generate the parameter files. The installation was successful but when I'm calling `skgen -h` I got the below-given error:
(skprogs) ram123@LAPTOP-TH1ME530:~$ skgen -h
Traceback (most recent call last):
  File "//opt/skprogs/bin/skgen", line 5, in <module>
    from sktools.scripts.skgen import main
ModuleNotFoundError: No module named 'sktools'

Any idea why this is happening?
Thanks in advance!
-Ram

**Comment by vanderhe** [comment]
Hi Ram,

my preferred way of installing the sktools is to create a dedicated virtual Python environment, like so:
```
git clone https://github.com/dftbplus/skprogs.git skprogs
cd skprogs
python3 -m venv /path/to/your/venvs/skprogs
source /path/to/your/venvs/skprogs/bin/activate
pip install sktools/
```
Could you give it a try and report back if everything works as intended? Remember that each time you would like to use the sktools that way, you have to source the activation script of the venv again, i.e.
```
source /path/to/your/venvs/skprogs/bin/activate
```

Best regards
Tammo
